--- #YAML:1.0
name:               POEx-HTTP-Server
version:            0.0700
abstract:           POE HTTP server
author:
    - Philip Gwyn <fil@localdomain>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dump:           1
    HTTP::Date:           1
    HTTP::Request:        1
    HTTP::Response:       1
    HTTP::Status:         1
    POE:                  1
    POE::Session::Multiplex:  0.0501
    POE::Session::PlainCall:  0.02
    POEx::URI:            0.0301
    Scalar::Util:         0
    Storable:             1
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
