---
abstract: 'POE HTTP server'
author:
  - 'Philip Gwyn <fil -at- cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POEx-HTTP-Server
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dump: 1
  HTTP::Date: 1
  HTTP::Request: 1
  HTTP::Response: 1
  HTTP::Status: 1
  POE: 1
  POE::Session::Multiplex: 0.06
  POE::Session::PlainCall: 0.03
  POEx::URI: 0.0301
  Scalar::Util: 0
  Storable: 1
version: 0.0902
